-- 3 Hatch Zergling
-- 3 Hatch Hydralisk
-- 3 Hatch Spire
-- 3 Hatch Lurkers
-- 4 Hatch before gas 
-- 3 Base Spire into 5 Hatch Hydra
-- 5 Pool
-- 6 Hatch (vs. Protoss)

-- 13 Pool Muta
-- 2 Hatch Muta
-- 3 Hatch Muta
-- 3 Hatch Lurkers
-- 3 Hatch Before Pool
-- 3 Hatch Zergling
-- 5 Pool
-- Fake 3 Hatch Muta (vs. Terran)
